vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.mouse = "a"
vim.opt.encoding = "utf-8"
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.autoindent = true
vim.opt.fileformat = "unix"
vim.opt.foldmethod = "indent"
vim.opt.foldlevel = 20
vim.opt.swapfile = false
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.wrap = false

-- vim.g.netrw_banner = false
vim.g.netrw_liststyle = 3
vim.g.netrw_browse_split = 3
